wandb_version: 1

activation:
  value: relu
actor_hidden_dims:
  value:
  - 256
  - 128
  - 64
clip_param:
  value: 0.2
critic_hidden_dims:
  value:
  - 256
  - 128
  - 64
decimation:
  value: 2
desired_kl:
  value: 0.01
empirical_normalization:
  value: true
entropy_coef:
  value: 0.01
episode_length_s:
  value: 5
gamma:
  value: 0.99
init_noise_std:
  value: 0.4
lam:
  value: 0.95
learning_rate:
  value: 0.0001
max_grad_norm:
  value: 1
max_iterations:
  value: 1500
num_envs:
  value: 2048
num_learning_epochs:
  value: 8
num_mini_batches:
  value: 512
num_steps_per_env:
  value: 24
save_interval:
  value: 500
schedule:
  value: adaptive
seed:
  value: 42
task:
  value: ARM-T-Lift-Cube-v0
use_clipped_value_loss:
  value: true
value_loss_coef:
  value: 0.5
