wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.16
    start_time: 1760529512
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 35
      4: 3.10.16
      5: 0.12.21
      8:
      - 8
activation:
  desc: null
  value: relu
actor_hidden_dims:
  desc: null
  value:
  - 512
  - 256
  - 128
clip_param:
  desc: null
  value: 0.1
critic_hidden_dims:
  desc: null
  value:
  - 512
  - 256
  - 128
decimation:
  desc: null
  value: 2
desired_kl:
  desc: null
  value: 0.01
empirical_normalization:
  desc: null
  value: true
entropy_coef:
  desc: null
  value: 0.005
episode_length_s:
  desc: null
  value: 20.0
gamma:
  desc: null
  value: 0.95
init_noise_std:
  desc: null
  value: 0.4
lam:
  desc: null
  value: 0.95
learning_rate:
  desc: null
  value: 0.002
max_grad_norm:
  desc: null
  value: 0.5
max_iterations:
  desc: null
  value: 1000
num_envs:
  desc: null
  value: 4096
num_learning_epochs:
  desc: null
  value: 8
num_mini_batches:
  desc: null
  value: 512
num_steps_per_env:
  desc: null
  value: 24
save_interval:
  desc: null
  value: 500
schedule:
  desc: null
  value: adaptive
seed:
  desc: null
  value: 42
use_clipped_value_loss:
  desc: null
  value: true
value_loss_coef:
  desc: null
  value: 0.34
